spring:
  application:
    name: ms-service-registry
  profiles:
    active: default
  config:
    import: configserver:http://user:s3cr3t@192.168.1.3:9090

#logging:
#  level:
#    com:
#      netflix:
#        eureka: DEBUG
#        discovery: DEBUG 